name: Deploy to IONOS with SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to IONOS via SFTP
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SFTP_DOMAIN }}
          port: 22                          # Puerto SFTP (normalmente 22)
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "dist/*"                 # Archivos locales en la carpeta build para transferir
          target: "/*"                # Directorio en el servidor IONOS (normalmente /htdocs/)